# Generated by Django 3.2.8 on 2021-10-29 12:54

from django.db import migrations, models
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.CharField(default=editor.models.id_generator, max_length=24),
        ),
    ]
