# Generated by Django 3.2.8 on 2021-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_document_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
