# Generated by Django 3.2.8 on 2021-11-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20211030_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
    ]
