# Generated by Django 3.2.8 on 2021-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_alter_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
