# Generated by Django 3.2.8 on 2021-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(max_length=110),
        ),
    ]
